name: Plugins install
description: Install the plugins listed on your .tool-versions file.
author: Victor Borja <vborja@apache.org>
runs:
  using: node20
  main: main.js
inputs:
  asdf_branch:
    description: asdf branch to clone
    required: false
    default: master
  skip_install:
    description: setup env without installing asdf
    required: false
    default: false
  tool_versions:
    description:
      If present, this value will be written to the .tool-versions file.
    required: false
